import { expect, test } from '@playwright/test'
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

import { checkPlanningProtocol, renderRecordIndex } from '../../scripts/planning-protocol'

function fixture(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), 'dyestopia-planning-'))
  for (const [path, source] of Object.entries(files)) {
    const absolute = join(root, path)
    mkdirSync(join(absolute, '..'), { recursive: true })
    writeFileSync(absolute, source)
  }
  return root
}

test('accepts cards and records that follow the planning protocol', () => {
  const root = fixture({
    'docs/planning/tasks/T-001-first-task.md': `---
id: T-001
type: task
title: First task
status: Todo
ordinal: 100
labels: [docs]
---
`,
    'docs/planning/tasks/I-001-an-idea.md': `---
id: I-001
type: idea
title: An idea
ordinal: 100
---
`,
    'docs/concepts/C-001-concept.md': `---
id: C-001
type: concept
title: Concept
status: Accepted
tasks: [T-001]
---
`,
    'docs/decisions/D-001-decision.md': `---
id: D-001
type: decision
title: Decision
status: Accepted
---
`,
    'docs/note.md': 'See `C-001` and `D-001`.\n',
  })

  const report = checkPlanningProtocol(root)

  expect(report.problems).toEqual([])
  expect(report.tasks).toHaveLength(2)
  expect(report.records).toHaveLength(2)
})

test('reports malformed cards, queue overflow, and broken record references', () => {
  const files: Record<string, string> = {
    'docs/planning/tasks/T-001-wrong-name.md': `---
id: T-002
type: task
title: Broken task
status: Nowhere
ordinal: first
---
`,
    'docs/concepts/C-001-concept.md': `---
id: C-001
type: concept
title: Concept
status: Accepted
tasks: [T-999]
---
`,
    'docs/note.md': 'See `D-999`.\n',
  }
  for (let index = 1; index <= 16; index++) {
    const id = `T-${String(index + 10).padStart(3, '0')}`
    files[`docs/planning/tasks/${id}-queued.md`] = `---
id: ${id}
type: task
title: Queued
status: Todo
ordinal: ${index * 100}
---
`
  }
  const root = fixture(files)

  const report = checkPlanningProtocol(root)

  expect(report.problems).toEqual(expect.arrayContaining([
    expect.stringContaining('filename must start with its id "T-002"'),
    expect.stringContaining('status "Nowhere" is not one of'),
    expect.stringContaining('ordinal must be a number'),
    expect.stringContaining('Todo holds 16 tasks, over the limit of 15'),
    expect.stringContaining('lists task T-999, which does not exist'),
    expect.stringContaining('references `D-999`, which is not a record on disk'),
  ]))
})

test('renders record indexes without any board output', () => {
  const rendered = renderRecordIndex('concept', [{
    file: 'docs/concepts/C-001-concept.md',
    id: 'C-001',
    kind: 'concept',
    title: 'Concept',
    status: 'Accepted',
    tasks: ['T-001'],
  }])

  expect(rendered).toContain('<!-- GENERATED by `npm run wiki` — do not edit. -->')
  expect(rendered).toContain('### Accepted (1)')
  expect(rendered).toContain('- `C-001` [Concept](C-001-concept.md) · `T-001`')
  expect(rendered).not.toContain('# Board')
})
